ASSOCIATION:
  POD-H1:
    iface_node: enp1s0
    node_ip: 200.239.93.94
    node_username: lasse-407
    pod_ip: 192.168.46.205

  POD-H2:
    iface_node: enp1s0
    node_ip: 200.239.93.93
    node_username: lasse-414
    pod_ip: 192.168.46.137
